site:
  title: LangChain4j for Quarkus
  start_page: quarkus-langchain4j:ROOT:index.adoc
content:
  sources: 
  - url: ./../
    branches: HEAD
    start_path: docs
ui: 
  bundle:
    url: https://github.com/quarkiverse/antora-ui-quarkiverse/releases/latest/download/ui-bundle.zip
    snapshot: true

asciidoc:
  attributes:
    kroki-fetch-diagram: true

output:
  dir: ./target/site